// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"github.com/joaopaulo-bertoncini/plugnfce-api/internal/application/usecase"
	"github.com/joaopaulo-bertoncini/plugnfce-api/internal/config"
	"github.com/joaopaulo-bertoncini/plugnfce-api/internal/infrastructure/database/postgres"
	"github.com/joaopaulo-bertoncini/plugnfce-api/internal/infrastructure/http/handler"
	"github.com/joaopaulo-bertoncini/plugnfce-api/internal/infrastructure/http/server"
	"github.com/joaopaulo-bertoncini/plugnfce-api/internal/infrastructure/messaging/rabbitmq"
	"github.com/joaopaulo-bertoncini/plugnfce-api/pkg/logger"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeAPI initializes the entire API application with dependency injection
func InitializeAPI(ctx context.Context, cfg *config.AppConfig, l logger.Logger) (*server.Server, error) {
	db, err := provideDatabase(ctx, cfg)
	if err != nil {
		return nil, err
	}
	nfCeRepository := postgres.NewNFCeRepository(db)
	publisher, err := providePublisher(cfg)
	if err != nil {
		return nil, err
	}
	nfCeUseCase := usecase.NewNFCeUseCase(nfCeRepository, publisher)
	nfCeHandler := handler.NewNFCeHandler(nfCeUseCase)
	companyRepository := postgres.NewCompanyRepository(db)
	planRepository := postgres.NewPlanRepository(db)
	subscriptionRepository := postgres.NewSubscriptionRepository(db)
	adminUseCase := usecase.NewAdminUseCase(companyRepository, planRepository, subscriptionRepository)
	adminHandler := handler.NewAdminHandler(adminUseCase)
	companyUseCase := usecase.NewCompanyUseCase(companyRepository, subscriptionRepository)
	companyHandler := handler.NewCompanyHandler(companyUseCase)
	planUseCase := usecase.NewPlanUseCase(planRepository)
	planHandler := handler.NewPlanHandler(planUseCase)
	subscriptionUseCase := usecase.NewSubscriptionUseCase(subscriptionRepository, planRepository, companyRepository)
	subscriptionHandler := handler.NewSubscriptionHandler(subscriptionUseCase)
	webhookRepository := postgres.NewWebhookRepository(db)
	webhookUseCase := usecase.NewWebhookUseCase(webhookRepository)
	webhookHandler := handler.NewWebhookHandler(webhookUseCase)
	string2 := providePort(cfg)
	serverServer := server.NewServer(nfCeHandler, adminHandler, companyHandler, planHandler, subscriptionHandler, webhookHandler, l, string2)
	return serverServer, nil
}

// wire.go:

// provideDatabase provides database instance
func provideDatabase(ctx context.Context, cfg *config.AppConfig) (*gorm.DB, error) {
	return postgres.NewDatabase(ctx, cfg)
}

// providePublisher provides RabbitMQ publisher
func providePublisher(cfg *config.AppConfig) (rabbitmq.Publisher, error) {
	return rabbitmq.NewPublisher(cfg.RabbitMQURL)
}

// providePort provides the server port
func providePort(cfg *config.AppConfig) string {
	return cfg.Port
}
